Issue #179295 task: Add webhook support for Shika/Vowel in TjNotifications
techjoomla/TJ-Notifications pull request #134
Opened 2022-02-08 13:05 UTC by praneettekdi

2022-02-10 14:45 UTC, manojLondhe requested changes

2022-02-10 14:45 UTC, manojLondhe commented on src/com_tjnotifications/admin/models/forms/webhookfields.xml
> +			name="use_gbwh_url"
lets indicate clearly as
use_gbwh_url => use_global_webhook_url

2022-02-10 14:45 UTC, manojLondhe commented on src/com_tjnotifications/admin/models/notification.php
> +				// webhook stuff starts here
phpcs

// webhook => // Webhook

2022-02-10 14:45 UTC, manojLondhe commented on src/com_tjnotifications/admin/models/notification.php
> +				// webhook stuff ends here
phpcs

// webhook => // Webhook

2022-02-10 14:45 UTC, manojLondhe commented on src/com_tjnotifications/admin/sql/install.mysql.utf8.sql
> +  `use_gbwh_url` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Use Global Config Webhook URLs',
rename as said above, everywhere

2022-02-11 03:28 UTC, praneettekdi commented on src/com_tjnotifications/admin/language/en-GB.com_tjnotifications.ini
> +COM_TJNOTIFICATIONS_FIELD_WEBHOOK_URL_SUBFORM_LABEL="Add Custom Webhook Urls"
ok

2022-02-14 13:46 UTC, merged